---
- name: Provision shadow base image
  hosts: localhost
  sudo: yes
  sudo_user: root
  tasks:
    - name: Copy ss-panel to remote
      copy: src=ss-panel dest=/root

    - name: Install docker-py
      pip: name=docker-py version=1.2.3 state=present

    - name: Start docker
      service: name=docker state=started enabled=yes

    - name: Build docker image
      command: docker build -t strikingly/ss-panel .

    - name: Run docker container
      docker:
        name: shadow
        image: "strikingly/ss-panel:latest"
        expose:
          - 80
        ports:
          - "80:80"
        state: restarted
        restart_policy: always
        volumes:
          - /root/ss-panel:/var/www:rw

    - name: Run cAdvisor container
      docker:
        name: cadvisor
        image: "google/cadvisor:latest"
        privileged: yes
        expose:
          - 8080
        ports:
          - "443:8080"
        state: restarted
        restart_policy: always
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /cgroup:/cgroup:ro
          - /var/lib/docker/:/var/lib/docker:ro
